### ISSUE TITLE
Improve UX of load simulation menu: one click sample loading

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto.frontend#149]
Every time I show live.geppetto.org to someone, I click the load simulation button (first click), click the dropdown menu to open it (second click), select an example (third click), and click load (fourth click).  I've noticed that this is a very common workflow as there is really not much you can do with geppetto before some simulation is loaded.   Pasting URLs and making custom geppetto files is probably a more advanced feature and it is ok to require the current number of clicks.

With a fairly trivial UI change, we could reduce the most common starting case to a single click and simplify the user experience:

1. Whenever there isn't a simulation loaded (like after the splash screen is closed), have the load simulation menu pop up by default. 
2. Modify the load simulation menu:
  1. change the drop down for the samples into a set of [vertical bootstrap buttons](http://getbootstrap.com/components/#btn-groups-vertical) so they are all immediately visible 
  2. if the user clicks a sample button, go ahead and load and don't bother making the user click the load button.  In this case the load button is only used for loading a custom URL so it can be moved next to that text box.  The cancel button can be left at the bottom and turned into a "close" button.
  2. put the sample loading buttons above the URL / Custom radio buttons and URL text box
  3. If user hits the Custom radio button, the whole menu will be too tall because of the textarea.  So, transform the buttons back into the dropdown menu as currently, but keep them above the radio buttons and the text area.  The load button will need to be put in here as well.  If the user hits the URL button, switch back to the buttons and remove the textarea

If we get to the point of having so many samples that the menu gets too tall, let's make two columns of buttons and make the menu wider.

**Comment by tarelli** [comment]
Superseded by dashboard.
