### ISSUE TITLE
Invalid Model URL Show error

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto.frontend#20]
If model url inside simulation file does not validate to url show error. 

- [ ] Handle exceptions by displaying error in client in model bundles
For example show error for simulation file with model url pointing to file system.
https://dl.dropboxusercontent.com/u/7538688/GeppettoSimulations/SPH_Elastic/GEPPETTO.xml

**Comment by tarelli** [comment]
Obsolete, these have been handled for a long time now
