### ISSUE TITLE
Add integration tests making sure recording can be streamed

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#229]
Once functionality for reading a Geppetto recording is in place and unit tests around reading a recording are in place [https://github.com/openworm/org.geppetto.core/issues/51] we need to stream recording data to the client and put together unit tests on qUnit around this, making sure data is being correctly received by the client and the simulation tree is being populated.

So to recap:
- [x] read a recording file from somewhere on the server's file system
- [x] add recording values to simulation tree on the backend
- [x] build a qunit integration test on the front-end to make sure values are being streamed as expected

**Comment by jrmartin** [comment]
The recording file now lives in the org.geppetto.simulation bundle. I couldn't get it to load if I had it store in the org.wormsim bundle

**Comment by gidili** [comment]
@jrmartin added checklist to this card! About the recording location, I think we need to discuss where the wormsim recording will live. If it can't be picked up cross bundle might be that we keep it somewhere else and then add it in deployment phase.

**Comment by jrmartin** [comment]
This card is pretty much done, need to commit my code. However,  there's a bug in which the simulator's simulate method is being called way more often than updates being send to the client. I think we are doing this on purpose not to overcrowd the client with updates. This is causing the recordings steps to be executed all within the time it takes to send the first and second update.

**Comment by jrmartin** [comment]
Okay , we're good, found a simple fix
