### ISSUE TITLE
Extend Connectivity Widget

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.frontend#235]
@borismarin this looks like a good option https://github.com/upphiminn/jLouvain. Maybe we would like to have some other community detection methods. Shall we go for a more complex js lib?

**Comment by adrianq** [comment]
See also #323

**Comment by borismarin** [comment]
Closing as openworm/org.geppetto#323 supersedes most of it, and graph analysis does not pertain to the conn widg exclusively.
