### ISSUE TITLE
Connectivity widget / domain specific info

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#238]
We have to design how to extract / access the information used by the connectivity views (conn. matrix, force layout, hive plot) from domain specific models.
It is possibly easier to illustrate that with an example: when visualizing networks defined in NeuroML, how should we (generically) instruct the widget to map the "weight" property of an element called "synapse" into the width of lines on the force diagram?

**Comment by borismarin** [comment]
We have to design how to extract / access the information used by the connectivity views (conn. matrix, force layout, hive plot) from domain specific models.
It is possibly easier to illustrate that with an example: when visualizing networks defined in NeuroML, how should we (generically) instruct the widget to map the "weight" property of an element called "synapse" into the width of lines on the force diagram?

**Comment by tarelli** [comment]
@adrianq @borismarin as per yesterday chat we need to see if the same approach we currently use to light up the neurons can be used to define a widget specific API to associate a specific variable (or pattern of variables, e.g. network.*.synapse) to either the width or the colour. @adrianq assigning to you to inform this point

**Comment by adrianq** [comment]
@tarelli I have just remembered what the actual problem about this approach is. Considering you have a tree like this one:
![screenshot from 2015-01-22 01 25 03](https://cloud.githubusercontent.com/assets/6850223/5848901/c1ee59ca-a1d5-11e4-8dc6-de5c2582ead1.png)

I want to say that the synapse_type depends on acnet2.I1L_0.NC_I1L_I1R_Generic_GJ0.elec_syn_1conns.Id 
or on acnet2.I3_0.NC_MCR_I3_Acetylcholine0.exc_syn_1conns.id
(id of the synapse node)

Obviously one option can be to change the way the model tree is populated so we have sth like this:
acnet2.I1L_0.NC_I1L_I1R_Generic_GJ0.synapse.Id but I do not think this is the right way as the instance path should be formed by the components id. I was thinking about using the domaintype field which is in the ANode.java. In the populatemodeltree we will set the domaintype="synapse" and then this approach makes sense. What do you think? Am I missing sth?

**Comment by tarelli** [comment]
@adrianq I see, let's start populating the domain type for the synapses so that we can descern different custom nodes, would that work?

**Comment by adrianq** [comment]
I have populated the domain type in server side. Now I will implement the mechanism in the frontend.
