### ISSUE TITLE
Add plot to preexisting canvas

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#239]
When right-clicking a functionNode and selecting _Plot Function_, it would be nice to have a sub-dropdown menu where the user would select from ["plot in new canvas", "plot in Plot_i"] where "Plot_i" are the i preexisting Plot widgets. 
Notice - it would be wise to keep the default behavior of generating a new Plot window if the user clicks "Plot function_", without the need of selection it from the dropdown.

**Comment by pgleeson** [comment]
+1

**Comment by adrianq** [comment]
I think it should be quite straight forward to implement this. Whenever I have some spare time I would like to fix/improve some things regarding the widgets that we have been talking during the last months.

**Comment by tarelli** [comment]
Tested on latest dev
