### ISSUE TITLE
Opposite camera rotation buttons don't perform opposite rotations

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto.frontend#244]
Steps to reproduce:

1. Load up the current OpenWorm muscle model
2. Move windows out of the way to see the 3D model
3. Zoom in about 5-6 clicks so the cylinder is nearby
4. Click the right-hand rotate button and observe how the model rotates once
5. Click the opposite left-hand rotate button and observe how the model does not go back to where it was  was before
6. Attempt similar rotations with the upper and lower rotate buttons.

Looking at this more closely, it seems like it is just a matter that the wrong command is being issued by the wrong button, so swapping the command between two neighboring buttons should work.

**Comment by tarelli** [comment]
Fixed with latest THREE release
