### ISSUE TITLE
Create Geppetto dashboard prototype

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#245]
A mockup for the dashboard can be found [here](https://docs.google.com/drawings/d/1G57X74SeZLD89XxInQlB7QtDUSAqdTdrUxUc5wwyxM0/edit)

- [x] Create Backbone model objects for the following DB entities
    - [x] GeppettoProject
    - [x] Experiment with parameters
    - [x] SimulationRun
- [x] Create mockup JS to populate dummy instances of the aforementioned objects
- [x] Create HTML page as per mockup using Bootstrap for grid/responsive layout
    - [x] Top pane with search bar and user info
    - [x] Left pane with grid of projects
    - [x] Right pane with details of a project and experiment
- [x] Implement JS logic to select a project resulting in population of the right pane
- [x] Implement JS logic to have a different status icon depending on the SimulationRun object
- [x] Implement JS logic to filter projects
- [x] Add placeholder icons as per mockup

**Comment by azee** [comment]
In mockup there is a status icon per each experiment. Experiments don't have status field - they have SimulationRuns list with status. Should we assume that there is only one SimulationRun for each Experiment or we have to select status of the last SimulationRun?

**Comment by gidili** [comment]
@azee yes, you can assume there is only one simulationRun per experiment for the time being!

**Comment by pgleeson** [comment]
Is there a snapshot of the prototype?

**Comment by tarelli** [comment]
![screen shot 2015-03-05 at 18 03 50](https://cloud.githubusercontent.com/assets/81127/6511049/ffd0039e-c361-11e4-9f89-f1b702f6c35b.png)

**Comment by pgleeson** [comment]
Looking good!

**Comment by borismarin** [comment]
What's a simlation?

**Comment by borismarin** [comment]
I really like the concept, BTW!
