### ISSUE TITLE
Refactor tree visualizer to perform lazy loading

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#247]
- [x] Add sub-pane if we are visualizing a type 
![ed8ec7ce-ab9c-11e4-8be7-549646cf262f](https://cloud.githubusercontent.com/assets/81127/6127422/a51e8e1c-b122-11e4-9d6e-e1e3aecef2eb.png)

**Comment by tarelli** [comment]
@adrianq this was an idea we had as a reminder

**Comment by adrianq** [comment]
This is done. Finally we have  lazy loading in two senses. We don't load the children treevisualsier nodes (html and js events) unless the user expand the folder. On the other hand,  if a  pointer is found (reference component in LEMS/NeuroML) and the user click on it a new treevisualiser is opened (still we need to improve the pointer label). All the javascripts objects for the tree (treevisualsier model) are created at the beginning as they are basically wrappers and they don't require too much memory/cpu.  Performance has improved dramatically but if needed we can create them  on demand  (when user clicks on a folder) as well.
