### ISSUE TITLE
Network activity widget design

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#248]
@cocoviper and @goldorac will be working on this. @tarelli to schedule a meeting to get the design started!

**Comment by cocoviper** [comment]
Our idea is to use multiple horizon charts (http://bl.ocks.org/mbostock/1483226) that we can expand to see more details. Also we would like to show the connections of one or multiple neurones selected (http://www.findtheconversation.com/concept-map).

With the library d3js ( http://d3js.org/ ) ,which is already used by the Connectivity Matrix , both the horizon charts and node connections are available.

**Comment by cocoviper** [comment]
Link of Michael McGuffin's presentation : http://www.michaelmcguffin.com/tmp/neuro-vis-mcguffin-2014June04/

**Comment by pgleeson** [comment]
Just as a general point, neuroscientists are used to noisy data and whatever package/widget is used for displaying the activity, it should be a faithful representation of the simulated data rather than being smoothed in any way (for individual cell voltage traces at least).

**Comment by cocoviper** [comment]
Since I won't be able to attend on the bi-monthly meeting here is where we are so far:
* The widget is up to date with version 0.2.2
* We can show data from VariableNodes.
* We can scan a tree for any VariableNodes and insert them in the datasets.
* We can click on a data row to expand it showing the InstancePath of the node and expanding the height.

Here is with 3 row expanded:
![image](https://cloud.githubusercontent.com/assets/4388524/6690101/b3a9e7fa-cc94-11e4-9c3f-86ee7bdd0fce.png)
Here is what it looks like when none are selected.
![image](https://cloud.githubusercontent.com/assets/4388524/6690176/4536285a-cc95-11e4-9c1b-449148160ae0.png)

In the upcoming weekend we plan on : 
* adding logic of groups of rows to associate with a cell for example.
* creating a wider range of color to see easily smaller changes.
* starting the connections links between rows.

**Comment by tarelli** [comment]
Looking good!

**Comment by cocoviper** [comment]
I have a couple questions.
Is there a way to know the maximum value of a variable node? 
Should I also look for Function node to show data?
Is there a simulation i can test with more than 5 variable nodes?

**Comment by tarelli** [comment]
@cocoviper see below:
1) it's not possible, you'll have to run the whole simulation to know. In the future when we'll have the results for all the time steps at once it would be possible to figure it out though.
2) I'm not sure I understand, to show which data? Function nodes belong to the model definition and are not dynamic, they could be plotted (something we support with the plotting widget) but I don't know of what use they would be to you, did you have something specific in mind?
3) You can fork the samples and add more variables to c302 by changing the following:
In the LEMS file
https://github.com/openworm/org.geppetto.samples/blob/master/LEMS/C302/LEMS_c302_A.xml
add more lines of the kind:
```
<Line id="ADAR" quantity="ADAR/0/generic_iaf_cell/v" scale="1mV" color="#a03600" timeScale="1ms" />
```
replacing both "ADAR" with whatever other neuron you want to plot (for all the available neurons see here https://raw.githubusercontent.com/openworm/org.geppetto.samples/master/LEMS/C302/c302_A.nml)

In the Geppetto file add the additional neurons that were added to the LEMS file also to variable watch:
```
Simulation.addWatchLists([{name:"hhvars",variablePaths:["c302.ADAL_0.electrical.SimulationTree.generic_iaf_cell.v","c302.ADAR_0.electrical.SimulationTree.generic_iaf_cell.v","c302.BDUR_0.electrical.SimulationTree.generic_iaf_cell.v","c302.I1R_0.electrical.SimulationTree.generic_iaf_cell.v","c302.I2L_0.electrical.SimulationTree.generic_iaf_cell.v","c302.PVDR_0.electrical.SimulationTree.generic_iaf_cell.v"]}]);
```

So say I want to add the neuron PVDL:
In the LEMS file I'll add 
```
<Line id="PVDL" quantity="PVDL/0/generic_iaf_cell/v" scale="1mV" color="#a03600" timeScale="1ms" />
```
And I'd expand variable watch like this:
```
Simulation.addWatchLists([{name:"hhvars",variablePaths:["c302.ADAL_0.electrical.SimulationTree.generic_iaf_cell.v","c302.ADAR_0.electrical.SimulationTree.generic_iaf_cell.v","c302.BDUR_0.electrical.SimulationTree.generic_iaf_cell.v","c302.I1R_0.electrical.SimulationTree.generic_iaf_cell.v","c302.I2L_0.electrical.SimulationTree.generic_iaf_cell.v","c302.PVDR_0.electrical.SimulationTree.generic_iaf_cell.v","c302.PVDL_0.electrical.SimulationTree.generic_iaf_cell.v"]}]);
```
There are 302 neurons in total so they should be enough!

**Comment by tarelli** [comment]
@cocoviper and @goldorac how is this going? any updates?

**Comment by cocoviper** [comment]
Sorry for the lack of updates. We has to finish and present our project to our school. Next week I want to make some final touches and update you on the project.
