### ISSUE TITLE
JS ConsoleElement object not created on first page load

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.frontend#254]
When loading Geppetto (I guess more often when it is loaded from OSB and when the cache has been cleaned) a js error occurs  and the page is not loaded properly. The problem is in this [line](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/GEPPETTO.Console.js#L277). It looks like we are not waiting for the DOM to be ready. I fixed a problem like this some months ago but it seems to be back. I will try to have a look at it when I had some spare time.

**Comment by anishshah101** [comment]
@adrianq Can you elaborate more on this issue?

I reloaded Geppetto with hard refresh as well as after clearing the cache. Didnt' receive the error.

Can you give some more information so that I can reproduce the bug? Also, which browser are you using?

**Comment by tarelli** [comment]
@anishshah101 it doesn't happen all the time and it never happens while running the server locally, it's a matter of timing I would start looking into something easier as the first one :)

**Comment by adrianq** [comment]
@anishshah101 Sorry I didn't come back to you. I will try to elaborate a little bit more although as @tarelli  said if you are starting to fix some bugs this is not one of the easiest. The problem has to do with the way we are loading the DOM and executing the jquery. If you want to execute some jquery commands on a html component you usually need to embed the jquery command in a:
```
$(document).ready(function() {}
```
We are doing something wrong because sometimes we are trying to execute a command on the Console component, i.e. (this)[https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/GEPPETTO.Console.js#L277] and the dom is not ready (Console is null). Therefore a js error occurs. Some components (Simulation buttons, zoom in/out, etc) are not loaded in the layout and the console can't be opened. It is a random error I guess because it depends on many things Internet speed, local js processing, elements being loaded asyncronous... This error can potentially happen in a different line also because of async execution. 
If you finally try to fix this bug let me know if I can be of any help. This time I will be faster in answering you :)

**Comment by adrianq** [comment]
After  a little bit of debugging I have some clues about where this error comes from... It doesn't come from the fact that the dom is not ready . We were already checking this [in here](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/GEPPETTO.Main.js#L151). The problem is that consoleElement.resizable [see here] (https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/GEPPETTO.Console.js#L279) requires jquery.ui to be loaded and sometimes (only in production environments) this is not happening. I will try to go on with this error later on...

**Comment by adrianq** [comment]
Ohhh god!! This issue is back in Town. @tarelli do you know someone with a Phd in require.js? Otherwise, can you just stab in the chest?

**Comment by tarelli** [comment]
@adrianq I've a feeling you are about the get one :)

**Comment by adrianq** [comment]
I have updated OSB with something that looks like a patch. As it is a random error I am not sure yet if I have finally fixed the error. 

@tarelli @pgleeson @borismarin if you see the error again can you please let me know? This error happens when you try to load a model in OSB and Geppetto is not loaded properly. You can't  see the Geppetto logo on the top left corner and any button on the top right corner , the model is not loaded and you are not able to open the console.  If this happens to you it would be great if you can take a screenshot with the javascript console opened for me.  Please clean the cache now so we are sure you are not loading the old javascripts files. Thanks!

**Comment by tarelli** [comment]
@adrianq thanks Adrian, fingers crossed. This issue has been officially awarded the HERO badge :)

**Comment by tarelli** [comment]
@adrianq do you have a PR for this?

**Comment by adrianq** [comment]
@tarelli Yes, I have. I haven't done it yet because I wanted to be sure it was actually a solution. After a few days I haven't see the error any more, so I will create a PR today.

I think I am going to print this issue and paste it on my room together with this image ![shit](http://data.whicdn.com/images/147574414/large.jpg)
