### ISSUE TITLE
Connectivity Widget is not working properly in Firefox

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.frontend#256]
![screenshot from 2015-03-02 10 16 56](https://cloud.githubusercontent.com/assets/6850223/6438942/b751c326-c0c5-11e4-96d9-c5605cdee4d3.png)

Also as you may see in the screenshot acnet2.baskets_12_0.electrical.select() is returning undefined for the cell. If I execute this command again once the model has been fully loaded and the script executed it works perfectly.

**Comment by adrianq** [comment]
@borismarin I think this is not happening anymore, right? Can we close the issue?

**Comment by borismarin** [comment]
I have tested it locally, seems to be working. Not sure what was causing that, though.
