### ISSUE TITLE
Prototype multiple collada file loading via Geppetto

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#257]
- [x] Create Geppetto simulation file which loads the collada cuticle and all the muscle cells

Ths simulation file will need to contain one parent entity named celegans and 96 children entities, one for the cuticle and 95 for each muscle cell.

**Comment by gidili** [comment]
First test of a simulation file loading 96 muscles here --> https://www.dropbox.com/s/u8mxi92j1lhk8qx/allMusclesGeppettoSim.xml?dl=0

![screenshot 2015-03-16 19 22 42](https://cloud.githubusercontent.com/assets/68134/6674590/aff1fddc-cc12-11e4-8198-f8270ad666c6.png)


To try on live (takes a good while to load as its downloading meshes from dropbox, once this is all local to the server it will be much faster) --> https://live.geppetto.org/?sim=https://www.dropbox.com/s/fq7irpkixr52krw/allMusclesGeppettoSim.xml?dl=1

**Comment by borismarin** [comment]
I think [this TODO marker](
https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/3d_visualization/GEPPETTO.SceneFactory.js#l194)
from my last refactoring might be relevant to this discussion.

**Comment by gidili** [comment]
@borismarin yeah that's relevant - I don't think we want to merge them as each is linked to an entity and we want to select entities independently (but maybe we can retain that even if we merge them).

**Comment by tarelli** [comment]
@borismarin I wouldn't think we want to ever merge collada files.

**Comment by borismarin** [comment]
BTW I've submitted a q&d (basically untested) PR directly through the gh
website (very nice "edit this file, submit PR" button), as I saw some ugly
code when looking for the line number to paste in the previous msg. I guess
that is not advised, but could someone see that it gets merged?
