### ISSUE TITLE
VisualReferences in Connection Lines

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto.frontend#259]
Ideally, connections lines should end up in the visual object reference id of the connection instead of the position of the entity. Current roadblock is that meshes need to be split into individual meshes for this to work, which is heavy. Local map with individual meshes prior to merge is kept in GEPPETTO.getVARS().visualModelMap, but those references don't give right position if scene is showing merged mesh instead of individual ones.

**Comment by tarelli** [comment]
The backend will be sending a 3D location of where the connection should end so it will take care of this.
