### ISSUE TITLE
Tree visualizer right click menu for cell in network

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#273]
It seems that the "show visual group" option seems to be behaving inconsistently for networks: see images below for ACNet2, before (extra menu items) and after (cell disappears) selecting it.
![screen shot 2015-04-21 at 19 17 47](https://cloud.githubusercontent.com/assets/3452783/7259630/81c2e780-e85c-11e4-8280-8436d41e4e37.png)
![screen shot 2015-04-21 at 19 18 01](https://cloud.githubusercontent.com/assets/3452783/7259636/8b54b1d4-e85c-11e4-8fbd-b55701becb7f.png)

**Comment by borismarin** [comment]
@adrianq @tarelli I am missing sthing here?

**Comment by jrmartin** [comment]
@borismarin Is it on live.geppetto? I'm running latest dev branches, and it's working alright with same sample. 
![acnet2](https://cloud.githubusercontent.com/assets/4562825/7259939/52fcc240-e81b-11e4-8ad0-f8625417d66e.png)

**Comment by jrmartin** [comment]
@borismarin Nope, disregard that, it's there. Tricky little bug, context menu didn't screw up until I launched for second time.

**Comment by borismarin** [comment]
Does your cell disappear as well?

**Comment by borismarin** [comment]
@jrmartin I've just merged dev, the cell does indeed disappear when you show vis group for cond densities.
