### ISSUE TITLE
Chainable methods for widget API

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#274]
I would suggest returning `this` instead of e.g. strings for widget methods, so we can chain them and get rid of temp vars `G.addWidget(1).setMessage('blah').setPosition()....`

**Comment by borismarin** [comment]
It seems that widget methods tend to return strings, which are in turn displayed in the console. @tarelli could we just explicitly log whatever there is to log and return `this`?

**Comment by borismarin** [comment]
@tarelli @adrianq @jrmartin It is probably easier to update those as we find them, I have already changed some of them for the conn widget while I was updating something else.

**Comment by tarelli** [comment]
I think I have done most of them, if some is not there let's open a bug or a PR. Btw now the object is not printed anymore to the console.
