### ISSUE TITLE
Consider bootstrap treeview

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#278]
Which seems more active than datgui
https://github.com/jonmiles/bootstrap-treeview
and leads to nicer views.
@adrianq @tarelli

**Comment by tarelli** [comment]
Sweet

**Comment by borismarin** [comment]
or that http://www.jstree.com/
or dig into d3 and have something like the osb taxonomy tree

**Comment by borismarin** [comment]
@tarelli @adrianq FYI, the first option (bootstrap) allows our long-awaited "search" , see http://jonmiles.github.io/bootstrap-treeview/
