### ISSUE TITLE
Returned javascript objects (e.g. widget.setData()) are printed to the console

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#289]
After the changes from @borismarin we are always returning the javascript object so that methods can be chained, this in general is a good thing, however we should improve the logic so that these do not get printed to the console, or at least not the naive printing that happens now.

**Comment by borismarin** [comment]
I haven't changed all methods to do that (see the card, and close it as you seem fit), but I guess that, as a general rule, 
> Make modifier methods return the host object, so that multiple modifiers can be invoked in a single expression.

**Comment by tarelli** [comment]
@borismarin returning is good, it's the printing that I think we could spare

**Comment by borismarin** [comment]
yep, I understand your first post, but I'd like to emphasize the pattern as it is so useful in this case. More of a guideline. And I guess that having a card for that will be infernal (finding every single instance where it is usable), so it's nice to keep it in mind for future dev.
