### ISSUE TITLE
Add pointers to source/dest for connections

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#291]
Currently, we (well, I haven't found a better way) have to do something like 
```
conn = entity.getConnections()[0]
source = conn.getParent();
target = eval(conn.getEntityInstancePath().substring(conn.getEntityInstancePath().indexOf('.') + 1));
```
in order to get the "endpoints" of a given connection. It would be simpler if a connection stored pointers (that probably relates to the Instance type issue) to _source_ and _dest_, for example.

**Comment by borismarin** [comment]
@tarelli could you please contextualize that?

**Comment by tarelli** [comment]
We should have getSource() and getEntity() methods on a ConnectionNode object

**Comment by borismarin** [comment]
I don't like these names - source depends on 'FROM', 'TO', right - so getFrom()/source() and getTo()/destination() are unclear? maybe getEndpoints() which returns tuple?

**Comment by tarelli** [comment]
You are right, although the methods could be smart enough to check the FROM/TO and return accordingly.
