### ISSUE TITLE
Event for getModelTree

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#292]
Various widgets would benefit if getModelTree emitted an event upon success - e.g. we could have lazy-loading TreeViews.

**Comment by tarelli** [comment]
+1 Probably every message we receive from the server should trigger an event.

**Comment by adrianq** [comment]
Working on this for populate model tree and simulation tree at the moment...let you know

**Comment by borismarin** [comment]
@adrianq and I have reworked it a little bit (so that events can call calbacks). Reopening for review by @tarelli.
