### ISSUE TITLE
Make the root node of RuntimeTree into CompositeNode

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#293]
So we can use Node methods on it.

@jrmartin would that require many changes?
@tarelli @adrianq

**Comment by jrmartin** [comment]
Could  those methods be added to RuntimeTree? That node is supposed to be seating at the throne of nodes.

**Comment by tarelli** [comment]
Even if it's the root why should it be any different than CompositeNode?

**Comment by jrmartin** [comment]
It would depend on what methods it requires

**Comment by tarelli** [comment]
I think @borismarin is interested in standard stuff that every Node has like its getSubdomainNode etc, correct?

**Comment by borismarin** [comment]
@tarelli yes, stuff like getSubNodeByDomainType, _all, which I've added to
Node

**Comment by jrmartin** [comment]
I don't think too many changes. https://github.com/openworm/org.geppetto.frontend/search?utf8=%E2%9C%93&q=runtimetree those are some of the refernces to runtimetree, as longs as those are changed and all simulations work fine then shouldn't a problem
