### ISSUE TITLE
Feed visual transformations to custom renderer

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#300]
Use "visual-transformations-backend-refactoring" for geppetto.core and geppetto.simulation bundles and the same branch ("visual-transformations", shorter name) for geppetto.frontend. Everything else off development bundles.

**Comment by gidili** [comment]
Update: it finally moves inside Geppetto, but there is a performance bottleneck somewhere. Currently troubleshooting that. 

![screenshot 2015-05-25 12 04 54](https://cloud.githubusercontent.com/assets/68134/7797359/da39cf32-02e2-11e5-8bf4-3d6e44635552.png)


cc: @tarelli @mihairaulea

**Comment by cheelee** [comment]
What are we currently using to profile the performance of Geppetto, if any? I'm thinking of using JVMTI to build a simple profiler, I've not yet found a good and flexible profiling tool for Java under the various frameworks used in Geppetto.

**Comment by gidili** [comment]
@cheelee in this particular case it's a clientside bottleneck, so I am using the chrome profiler to see where it hangs. For server side I never had to do hardcore profiling so mainly used log statements in the code to time stuff, but that's just me!

**Comment by cheelee** [comment]
@gidili Ah cool. I'll see if I can come up with something simple and hopefully useful to the developers server-side where performance bottleneck analysis is concerned. Might take a while though, while I am familiar with Java, I'm not particularly familiar with the various frameworks over which the simulation code is constructed in Geppetto. Thanks!

**Comment by gidili** [comment]
@cheelee it would be very useful! Keep us posted :+1:

**Comment by gidili** [comment]
It moves... but still slow.

![screenshot 2015-05-26 20 43 17](https://cloud.githubusercontent.com/assets/68134/7833464/01d78994-045f-11e5-90c2-d34af4b15f36.png)

To try this:

- get visual-transformations branch for geppetto.core / geppetto.frontend / geppetto.simulation
- everything else can point to development branch
- drop appdata folder into virgo root --> https://www.dropbox.com/s/7fzqhsp0qi489yr/appdata.zip?dl=0
- override GEPPETTO.init.js to always instantiate the custom renderer with [this file](https://www.dropbox.com/s/j86o6wxch48b3po/GEPPETTO.Init.js?dl=0)
- use the sph-animation simulation file --> https://www.dropbox.com/s/5r8r8qhjh6dv791/wormsim-sph-animation.xml?dl=1

**Comment by gidili** [comment]
After doing some profiling and tweaking some nice progress can be seen here:

https://www.youtube.com/watch?v=H7lmv7YtGxk

Still not perfect, but will merge this into the datamanager branch and between those improvements and the compression stuff (that won't affect the animation speed but the transfer of data) that's coming we'll get it where it needs to be.

**Comment by gidili** [comment]
Currently re-doing this in the datamanager branch as everything changed.
