### ISSUE TITLE
Experiments UI

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#301]
In the simulation environment we need a way to display the available experiments, switch between them, run them, etc, see [mockup](https://docs.google.com/drawings/d/1Bt-0Pdxe4cdlpsMWLaT6EzRr5hiHYsASghXql0GPCrM/edit)
- [x] Review Mockup
- [x] Decide on final version
- [x] Add UI Elements
- [x] Test/QUnit

**Comment by cheelee** [comment]
I've sent a request for access to the mockup document to see if there's anything I could help out with, and to see if there's something I could propose to add in the future. Thanks!

**Comment by tarelli** [comment]
Permission fixed anyone with the link should be able to view now
