### ISSUE TITLE
Add mechanism to run Geppetto scripts based on events triggered (i.e. select entity)

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#304]
We need to be able to run a custom script (i.e. open a tree widget with info for a given entity) in response to a Geppetto event (i.e. when the entity is selected by the user). 

We need this this functionality inherent in Geppetto rather than having to add another widget to wire the events to the handling logic.

Would work something like the following: 

```
G.addEventListener(Events.Select,function(event));
```

Reference on Geppetto events: http://docs.geppetto.org/en/latest/events.html

**Comment by borismarin** [comment]
See what @adrianq and I made here: https://github.com/openworm/org.geppetto.frontend/commit/39039fa7ca773def0a9c97070569bf55e95c4d3e
Notice: the whole event framework needs refactoring. There are some unspeakable things lurking there...

**Comment by gidili** [comment]
@borismarin @adrianq so I read this correctly that any widget can register for any Geppetto event and define the call back to respond to it? Where are the registeredEvents (and callbacks if any) defined for the tree visualizer for instance? 

The beer count is going up :beers:

**Comment by gidili** [comment]
@borismarin @adrianq I see [these events and handlers](https://github.com/openworm/org.geppetto.frontend/blob/39039fa7ca773def0a9c97070569bf55e95c4d3e/src/main/webapp/js/widgets/treevisualiser/treevisualiserdat/TreeVisualiserDAT.js#L76) but can't see where (or if) it's ever pushed to registeredEvents list with a "registerEvent" call

**Comment by jrmartin** [comment]
@gidili  There's a bit of documentation here http://docs.geppetto.org/en/latest/events.html

**Comment by gidili** [comment]
@jrmartin alright so the change @borismarin linked allows to also pass a callback when registering to an event

**Comment by tarelli** [comment]
@gidili still needed?

**Comment by gidili** [comment]
@tarelli not sure but regardless I think it's done by @borismarin and @adrianq (see comments above)
