### ISSUE TITLE
Alert dialogs covered by console

### ISSUE THREAD

**Issue by samredway** [openworm/org.geppetto.frontend#305]
The console has focus over alert dialogs. So when you click load simulation from the main screen and then choose your simulation you cannot click the load button unless you close the console first. The same when the "are you still there zzzzz" alert comes up. You have to close the console to click OK. It is a minor thing but I feel it would be a better user experience if the alerts had focus automatically so you can click them close and carry on with your work without having to close and then reopen the console.

**Comment by tarelli** [comment]
+1 @samredway agreed!

**Comment by gidili** [comment]
Yes that's annoying - hopefully it's a matter of playing with z-indexes!

**Comment by ashishkadam** [comment]
I am not able to replicate the issue, has it been fixed?

**Comment by tarelli** [comment]
@anishshah101 This issue has most likely be taken care of in the datamanager branch which we'll be releasing in the next week or so. Let me test it and I'll get back to you if not you can help fixing it once we merge back to development!
