### ISSUE TITLE
Refactor binary message transmission

### ISSUE THREAD

**Issue by frenkield** [openworm/org.geppetto.frontend#309]
Currently there are 2 types of binary messages transmitted from server to client. One type contains a compressed JSON scene update and the other contains a binary experiment file. Binary messages are routed in Javascript according to a one-byte header.

The task here is to generalize the binary message routing and possibly unify it with the existing routing mechanism for text (JSON) messages.

**Comment by tarelli** [comment]
@frenkield Looks good to me!

**Comment by frenkield** [comment]
Hi @tarelli,

Sorry for taking so long on this. I refactored the code a bit but I'm having trouble testing it.

I'm running the Hodgkin-Huxley experiment but it never enters the file transmission code in Websocket Connection. The method is here:
* https://github.com/openworm/org.geppetto.frontend/blob/datamanager/src/main/java/org/geppetto/frontend/controllers/WebsocketConnection.java#L154

How do I run/view the experiment so that it uses the file transmission code?

Thanks!
David

**Comment by adrianq** [comment]
Hi @frenkield! hhcell.electrical.downloadModel() should do the trick!

**Comment by frenkield** [comment]
Thanks, @adrianq!

**Comment by tarelli** [comment]
@frenkield @adrianq this was done right?

**Comment by adrianq** [comment]
Some refactor work was done by @frenkield but I think he wanted to work on this a little bit more...

**Comment by tarelli** [comment]
@frenkield hey David, do you wanted to do some more in this area? How's France going?:)
