### ISSUE TITLE
Improve Tree Visualiser widget

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#312]
There is some dirty code that can be improved in the TREEVisualiserDAT, in particular all the ad-hoc things happening inside the prepareTree can be solved in a more elegant way.

**Comment by tarelli** [comment]
@adrianq another one...

**Comment by adrianq** [comment]
@tarelli already taking care of this... Is this the issue morning? ;) Shouldn't you be listening to the other speakers?

**Comment by tarelli** [comment]
@adrianq indeed :)
