### ISSUE TITLE
Improve plotting widget

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#328]
Some work from @jrmartin trying a new plotting widget based on [Epoch](https://fastly.github.io/epoch/) [here](https://github.com/openworm/org.geppetto.frontend/tree/epoch-try-out).

**Comment by ccluri** [comment]
When looking at large datasets (like microelectrode array data) it is useful to heavily undersample and plot, and then possibly have in a rectangle tool, that zooms-in into the areas of interest - when high-res traces are show, See https://www.youtube.com/watch?v=VYnKB2grEVM and now vispy for instance.

**Comment by ccluri** [comment]
High density electrode grids, 4096 electrodes for example - One would want to look at this data as a video - as a changing 2D image of spatial potential profile.

**Comment by ccluri** [comment]
Perhaps more relevant to simulations. Effective raster plotter facility. [Example](http://seis.bris.ac.uk/~mb0184/projects/dtsonn/images/raster_all_wlines.jpg)

**Comment by adrianq** [comment]
Moving this to the backlog. I don't think this is something we can take care of in the near future...

**Comment by tarelli** [comment]
Refactored a lot of code for the currently existing one. Now it's much faster and performant, doesn't seem to require anything else for time being.
