### ISSUE TITLE
Explore using a WebWorker to parse/decompress JSON from the server

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#333]

**Comment by gidili** [comment]
@tarelli @adrianq @frenkield @jrmartin I wonder if moving the parsing and decompression into a background thread clientside would make everything smoother. 

We are currently using webworkers for:
- polling status of experiments
- stepping the recordings while they are being played

From what I now understand about webworkers there's no need to use webworkers for the above but it might be quite beneficial to employ them when parsing / decompressing. It's probably a tradeoff scenario here too where it stops making sense if the message from the server is too small.

**Comment by tarelli** [comment]
@gidili note that we are not compressing if the message is below a certain size specified server side

**Comment by gidili** [comment]
@tarelli I am aware of that, not sure what the threshold is though and it might still make sensed to parse the response in a background thread regardless. The point is that having workers like we have for very inexpensive operations (one for doing a request every second and one for pretty much doing a setInterval) might make no sense and might make things worse given the cost of spawning threads. But we'll never know till we try. Probably low priority since things are working quite well right now.

**Comment by tarelli** [comment]
We should definitely experiment, I'd be interested in seeing how putting
three.js inside a worker behaves to mention another one

**Comment by gidili** [comment]
Also worth exploring (but low priority) ... using a shared worker to handle connections of all the geppetto tabs open in a given session (this is what twitter does if you open a bunch of tabs). Might make things smoother when opening many tabs.

**Comment by frenkield** [comment]
Hi @tarelli and @gidili,

I'm not sure if this helps but at some point Virgo will (hopefully) support per-message deflate for web sockets. So then the browser will decompress natively and performance should be much better.

Also, I'm in the process of relocating to France (for 6 months) so I'll be out of commission for a while. I'll check in periodically though.

Thanks!
David

**Comment by tarelli** [comment]
Thanks @frenkield, enjoy France! Let me know once you are settled in if you have some bandwidth :)
