### ISSUE TITLE
Bug with lines visualization and some networks

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#348]
When a network position different instances of a cell in a different place they all endup in the origin when using lines visualization

**Comment by mattearnshaw** [comment]
still occurs [here](http://comodl.org/projects/thalamocortical?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FThalamocortical%252Fmaster%252FNeuroML2%252FpythonScripts%252Fnetbuild%252FTestSmall.net.nml) for example

**Comment by tarelli** [comment]
@mattearnshaw can you merge the latest of dev in this branch :)

**Comment by tarelli** [comment]
@mattearnshaw can you retest with the latests?
