### ISSUE TITLE
Enhanced visualization for network activity

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#350]
Have moving light particles moving on a morphology to represent network activity.

**Comment by slarson** [comment]
Oooh.  How's it gonna be enhanced? :)

**Comment by tarelli** [comment]
@slarson description updated @felipetavares working on a prototype for this

**Comment by tarelli** [comment]
@felipetavares can I move to "In progress?"

**Comment by felipetavares** [comment]
@tarelli Yes

**Comment by pgleeson** [comment]
@tarelli @felipetavares could you give some more details of this, is it going to be a feature just to provide some nice visuals, or will it be based on recorded network activity? Most of the networks on OSB at present are pretty small (and so synaptic weights are scaled up to get cells to fire), but more accurate ones will involve many cells spiking simultaneously and there would be a lot of spike transmission between cells... [This](http://www.opensourcebrain.org/projects/weileretal08-laminarcortex?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FWeilerEtAl08-LaminarCortex%2Fmaster%2FNeuroML2%2FCortexDemoHH.net.nml) could be used for testing now (should run via jNeuroML_NEURON), but [this](http://www.opensourcebrain.org/projects/weileretal08-laminarcortex?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FWeilerEtAl08-LaminarCortex%252Fmaster%252FNeuroML2%252FCortexDemo999.net.nml#) (no connections yet) would ideally be the scale of network that would be nice to see activity in.

Wrt detailed morphologies, propagation of depolarization along the dendrites is often shown using rainbow/heatmap colouring (e.g. see Movie_*.avi [here](http://figshare.com/articles/Glutamate_Bound_NMDARs_Arising_from_In_Vivo_like_Network_Activity_Extend_Spatio_temporal_Integration_in_a_L5_Cortical_Pyramidal_Cell_Model/1006889)). This might be a better feature to implement than a single particle of propagating activity.
