### ISSUE TITLE
Extend PopupWidget to support Geppetto node pointers

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#352]
Add API function to popupWidget
looks inside anchor elements for the instancePath attribute.
```
addCustomNodeHandler(function(), eventType, domainType)
```
eventType could be click (default if it the parameter is not passed), hover, doubleClick, etc.)
eventType and domainType are optional.

**Comment by gidili** [comment]
Hi @adrianq - @tarelli mentioned you were working on the other part of this, are there any samples with the instancePath attribute?

**Comment by adrianq** [comment]
Hi @gidili, you will have to checkout the branch neuroMLSummary for frontend, core and neuroml model interpreter bundle. When you execute getModelTree you will get a node of type HTMLMetadatanote, this is the one you have to work with. In there you will have some links with instancePath attribute.

**Comment by gidili** [comment]
@adrianq great thanks! Is the HH model a good one to work with or which one do you suggest?

**Comment by adrianq** [comment]
HHmodel should be fine. I will be in the gchat, drop a line if you have any problem.
