### ISSUE TITLE
Multiple select affecting transparency and not being cleared

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#359]
If multiple entities are selected then the transparency of all front facing entities is changed and no cleared when a single item is selected or selections cleared.

Suspect this may have changed with three.js upgrade as never noticed in testing before r73.

This doesn't appear to be opacity as even when manually set the entity appears solid.

**Comment by Robbie1977** [comment]
@tarelli can you replicate on your server? Just select 2 transparent objects (doesn't matter which - affects all).

**Comment by tarelli** [comment]
@Robbie1977 yup, reproduced this, I'll try to look into it tomorrow

**Comment by tarelli** [comment]
@Robbie1977 this was fixed right?

**Comment by Robbie1977** [comment]
Seems to be - can't reproduce it.
