### ISSUE TITLE
Connectivity widget improvements

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#388]
- [x] add toolbar / button to switch between matrix / chords / hive / force
- [x] improve default [node/link -> category  mappings,](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/widgets/connectivity/Connectivity.js#L54) now that we have proper types
- [x] categorical colormaps are hardcoded (usually comport 20 categories). Make that configurable via _options_ obj.
- [x] ticks for chord diagrams are hardcoded. Make that configurable via _options_ obj.
- [ ] legends are not very flexible. Make that configurable via _options_ obj.
- [x] add casper tests

Open questions for everyone out there (yes you too):
- [ ] how should we represent more than one edge connecting the same nodes (multigraph) - in particular, in the matrix view? what about bidirectional connections (we always assume single directed edges)

**Comment by LordKrabo** [comment]
@borismarin Should I add this to sprint 75?

**Comment by LordKrabo** [comment]
Added to sprint 76.

**Comment by tarelli** [comment]
@borismarin is happy to guide whoever volunteers on this card

**Comment by LordKrabo** [comment]
@borismarin if I were to help out what should I do?

**Comment by borismarin** [comment]
@LordKrabo let's schedule a meeting

**Comment by borismarin** [comment]
@LordKrabo started some experiments [here](https://github.com/openworm/org.geppetto.frontend/tree/connW-config-gui)

**Comment by LordKrabo** [comment]
@borismarin Those would be the experiments under https://github.com/openworm/org.geppetto.frontend/tree/connW-config-gui/src/main/webapp/js/widgets?

**Comment by mattearnshaw** [comment]
I think this is wrapped up...
