### ISSUE TITLE
Selection of point cloud OBJ items not changing colour

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#398]
They seem to select fine just that they don't turn yellow (like solid OBJs).

Test example: http://129.215.164.244:8084/org.geppetto.frontend/geppetto?load_project_from_url=http://vfbsandbox3.inf.ed.ac.uk/do/geppettoJson.json?i=VFB_00021153,VFB_00021850%26t=VFBt_001%26d= 

Running latest development branch as of last wednesday.

**Comment by tarelli** [comment]
I noticed also, I will have a look tomorrow!

**Comment by Robbie1977** [comment]
Might be worth having a look at the selection rules for point clouds as probably need to act as normal OBJs in that multi click should tunnel through selection as you can see from the example above it's very difficult to click to select anatomy when expression is so general as in optic lobes.
