### ISSUE TITLE
API for dynamic model creation

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#399]
- [x] branch frontend
- [x] create Datasource wrapped object
- [x] create Datasource objects on model loading
- [x] create ImportType wrapped object
- [x] implement fetchVariable method on datasource
- [x] update list of all potential instance paths for new variables
- [x] implement resolve method on ImportType
- [x] integrate with backend
- [x] test EVERYTHING

**Comment by borismarin** [comment]
define _model_

**Comment by gidili** [comment]
A picture is worth a thousand words:
![model_06](https://cloud.githubusercontent.com/assets/68134/13747014/28b913e6-e9ee-11e5-9a29-87b84e46d9c4.jpg)

**Comment by borismarin** [comment]
Hm good luck designing an API for that...

**Comment by gidili** [comment]
@borismarin LOL - added some text at the top, basically we are adding the ability to interrogate external data sources and thus import variables/types into the Geppetto model at runtime
