### ISSUE TITLE
Console autocomplete for injected capabilities

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#400]
The API injected through the capabilities is not available through our JS console autocomplete.

**Comment by tarelli** [comment]
Moved it to Sprint 71

**Comment by Robbie1977** [comment]
@gidili Autocomplete in ontology branch has become a tad overzealous - you can't actually delete one autocomplete kicks in without jumping the cursor to break to match. Works a lot slower and hence more usabily in live.geppetto.org

**Comment by gidili** [comment]
@Robbie1977 That's odd - I don't think we touched anything, is this in the console or in the spotlight?

**Comment by Robbie1977** [comment]
console

**Comment by Robbie1977** [comment]
Load: http://129.215.164.244:8084/org.geppetto.frontend/geppetto?load_project_from_id=10
and type 'VFB_00000001.VFB_00000001_m' then try and backspace

**Comment by gidili** [comment]
@Robbie1977 yes, I tried after your first comment. Weird!

**Comment by LordKrabo** [comment]
Hi @gidili can I move this to Sprint 74?

**Comment by gidili** [comment]
@LordKrabo yes, thanks!

**Comment by gidili** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TLHcDfCP&#x2F;31-fix-autocomplete-in-console-for-injected-capabilities"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Fix autocomplete in console for injected capabilities</a>
