### ISSUE TITLE
Use plotly for plot widget

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto.frontend#404]
Replace flots library with plotly

**Comment by jrmartin** [comment]
Update: This one is coming along slower than I thought, but here's an update with the new library working for plots that are updated one step at a time. It's pretty neat the axis are updated as new data is added. It's slowed down by the gif maker program recording screen. 

![plotly-demo-dynamic](https://cloud.githubusercontent.com/assets/4562825/14266228/a4b0f3f4-fa7b-11e5-8062-f1f1d4598cc2.gif)

**Comment by tarelli** [comment]
@jrmartin thanks, it looks great! I haven't yet taken the code down locally, but I will soon! From the GIF it looks like the data is always appended rather than having a scrolling effect as in the current widget, is that the case/intended?

**Comment by jrmartin** [comment]
@tarelli Not intended, still fixing some bugs and performance. Will commit some of those by end week once I get out of 3G data only land

**Comment by tarelli** [comment]
:+1:

**Comment by jrmartin** [comment]
I fixed some bugs and latest is on repo, but still buggy. It was enough to test dynamic plotting step by step,  and see our current plot is still faster.  The browser gets stuck by calling the redraw() method on plotly many times, no other efficient way to redraw faster..

**Comment by tarelli** [comment]
@jrmartin thanks for pushing this forward! Maybe in that case it's something that we could have as an alternative rather than as a replacement unless we find a way to have comparable performances.

**Comment by LordKrabo** [comment]
Added to sprint 75 @jrmartin @tarelli
