### ISSUE TITLE
Fix .plotXYData method in Plotting widget

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#407]

**Comment by tarelli** [comment]
@niteshthali08 is this done?

**Comment by niteshthali08** [comment]
@tarelli : getTimeSeries(), getUnit() functions are undefined on the Instance which I create. I can close this once this functions are fixed. I don't know how to fix this. Could you please help me with that ? Also I want to know the place from where to call .plotXYData() function on loading the project.

**Comment by tarelli** [comment]
Ok, do you have everything pushed?

**Comment by niteshthali08** [comment]
Ya i have pushed it to nwb branch. 
@tarelli I am getting following error after updating to 0.2.9 when i do maven build on core.
Niteshs-MacBook-Pro:org.geppetto.core Nitesh$ mvn compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Geppetto Core Bundle 0.2.9
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.geppetto:model:jar:0.2.9 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.288 s
[INFO] Finished at: 2016-04-16T14:12:11-07:00
[INFO] Final Memory: 8M/156M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project org.geppetto:core:bundle:0.2.9: Failure to find org.geppetto:model:jar:0.2.9 in http://repository.springsource.com/maven/bundles/release was cached in the local repository, resolution will not be reattempted until the update interval of com.springsource.repository.bundles.release has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

When i try it via eclipse, "Edit configuration and launch" pop up comes asking for goals, profile etc. 
What is wrong here?

**Comment by tarelli** [comment]
@niteshthali08 what do you see when you try and do mvn install of org.geppetto.model?

**Comment by niteshthali08** [comment]
@tarelli:  I tried couple of things and it is working now :)

**Comment by tarelli** [comment]
@niteshthali08 I fixed few things, getTimeSeries, getUnit and the call exceeded stack. There is now a script.js in the sample that plots automatically, see screenshot. 

![screen shot 2016-04-21 at 21 46 58](https://cloud.githubusercontent.com/assets/81127/14723790/b636fb36-080a-11e6-9cea-fa19d6a6fbbf.png)

**Comment by tarelli** [comment]
@niteshthali08 you will need 0.2.9 for all the other bundles since I updated the branches to 0.2.9

**Comment by niteshthali08** [comment]
Thanks @tarelli 👍
The Hodkin-Huxley Neuron plots gone weird now.

**Comment by tarelli** [comment]
Whoops, what have I done? :) I'll check what's up with those

**Comment by tarelli** [comment]
@niteshthali08 fixed now!

**Comment by niteshthali08** [comment]
yeah but nwb got screwed up now :P

**Comment by tarelli** [comment]
Nope it's working I need to push the updated script but now you also touched the repo and I'm doing a merge :)

**Comment by niteshthali08** [comment]
Yeah got it.. 
Thanks
