### ISSUE TITLE
Flickering 3D Scene

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto.frontend#411]
Live geppetto scene flickers after loading a model. Tested in Chrome using Windows 8.

![flickering-scene](https://cloud.githubusercontent.com/assets/4562825/14290743/21b6045e-fb15-11e5-9b5d-cf875082ebdc.gif)

**Comment by jrmartin** [comment]
Bug is gone in live and local in my windows machine.

**Comment by gidili** [comment]
@jrmartin some update or something?

**Comment by jrmartin** [comment]
@gidili Windows 10 update, my chrome browser was reset in the process. Also just switch from Eclipse Juno to Luna, but that only accounts for local.
