### ISSUE TITLE
Migrate from JSXTransformer to Babel

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#412]
JSXTransformer is currently deprecated. Babel has the same features and is recommended for the latest version of react (0.14x). 

For reference: https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

Migration info: http://www.phpied.com/from-jsxtransformer-to-babel/

**Comment by gidili** [comment]
As a note, currently working on this swap in the ontology branch.

**Comment by LordKrabo** [comment]
Hi @gidili, add this one to Sprint 75 or 74?

**Comment by tarelli** [comment]
Whatever you guys do rememeber to check that "mvn install -P master" still works for org.geppetto.frontend

**Comment by gidili** [comment]
After further consideration, getting rid of babel for now - the JSXTransformer is working fine and that's what's used in the latest react examples. We don't really need to switch for now and babel comes with a baggage of stuff that we dont need for the time being (JSXTransformer is a subset of the stuff that comes with babel).
