### ISSUE TITLE
Hide / show instance issue

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#414]
Documenting this bug I noticed on the HH demo:

![screenshot 2016-04-13 12 33 08](https://cloud.githubusercontent.com/assets/68134/14492086/df92e4aa-0174-11e6-8510-a1a9fc0d6646.png)

It seems that when it's hidden it gets removed from the scene:

![screenshot 2016-04-13 12 37 46](https://cloud.githubusercontent.com/assets/68134/14492102/fb0a9d90-0174-11e6-94a8-6d82609c8f45.png)

Also another inconsistency after calling .hide:

![screenshot 2016-04-13 12 34 49](https://cloud.githubusercontent.com/assets/68134/14492128/2b596486-0175-11e6-9a7f-43c483ec87e7.png)

For some reason it works in the acnet example.

**Comment by tarelli** [comment]
Fixed in the ontology branch.
