### ISSUE TITLE
Make selection cycle when clicking on cloud point, same as with other OBJs

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#417]

**Comment by Robbie1977** [comment]
This is due to the opacity being set to 1 and hence takes selection priority over all transparent objects.
I've resolved it by lowering the opacity as we do with the solid OBJs.
https://github.com/VirtualFlyBrain/VFB/commit/a96a4e266cc56d68003f8877e2a9ce05f29a23b8
