### ISSUE TITLE
control panel info button not updating widget title

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#425]
widget title not set as is done by the current type(s) link actions.

**Comment by gidili** [comment]
@Robbie1977 on [GEPPETTO.ControlPanel.setControlsConfig](https://github.com/openworm/org.geppetto.core/blob/ontology/src/main/resources/projects/OntologyTest/script.js#L7) in the script, change the action bit for the info button:

`"info": { "id": "info", **"actions": [ "G.addWidget(1).setData($instance$)" ]**, "icon": "fa-info-circle", "label": "Info", "tooltip": "Info" }`

To do the same as to when it's triggered by a type click (this is set on [GEPPETTO.ControlPanel.setColumnMeta](https://github.com/openworm/org.geppetto.core/blob/ontology/src/main/resources/projects/OntologyTest/script.js#L4)):

`"action": "var displayTexxxt = '$entity$'.split('.')['$entity$'.split('.').length - 1]; G.addWidget(1).setData($entity$[displayTexxxt + '_meta']).setName(displayTexxxt).addCustomNodeHandler(customHandler,'click');"`

Notes: 

- those links point to ontology branch, not sure where the ontology sample ended up after the development merge @tarelli.
- displayTexxxt - I used that "strange" variable name to avoid naming collision, you should be able to do it all in one line... 😄

**Comment by tarelli** [comment]
This is now fixed.
