### ISSUE TITLE
Sometimes applying a visual group causes a morphology to disappear

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#433]
From Padraig: When viewing cell with 1 cell region (e.e. hodgkin_huxley_tutorial, with just soma group), select Cell Visual; select Show Visual Groups (right click CellRegion) and the cell (or all network) disappears.

**Comment by jrmartin** [comment]
Tested and reproduced on OSB and local geppetto. Debug console points to bug in GEPPETTO.SceneController.showVisualGroups(), when it splits a merged mesh into individual ones in splitGroup() method
