### ISSUE TITLE
Query Widget

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.frontend#437]

**Comment by gidili** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;t33wG3bs&#x2F;32-80-query-component"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (80) Query Component</a>

**Comment by LordKrabo** [comment]
Hi @gidili and @tarelli should I push this to sprint 82?

**Comment by tarelli** [comment]
@LordKrabo yes, thanks, doing some final touches :)
