### ISSUE TITLE
UI theming

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#441]
motivation: it would be useful to have a 'light colour theme' in order to grab screenshots for publications, posters (which usually have white bg). 

In general, we could have a mechanism for setting UI themes (changing the bg color is not enough as widget canvases, butttons etc need to be recoloured accordingly); something like `G.setColourTheme('light'|'dark'|...)`

It seems that jqueryui already has a theming mechanism:
http://jqueryui.com/themeroller/

**Comment by pgleeson** [comment]
+1. I'd also like it if there were a few standard themes and these could be accessed with 

    G.setColourThemeLight()
    G.setColourThemeDark()

it makes it easier than having to remember the names of the themes and with 

    G.setColourTheme + tab

you see all options

**Comment by gidili** [comment]
@borismarin @pgleeson a while back I wrote a script to theme geppetto for the wormsim, can be seen here --> https://github.com/openworm/org.wormsim.frontend/blob/master/utilities/applyWormSimTheme.py

What you guys are talking about is of course much nicer from the end user perspective but if you want a quick and dirty way for taking screenshots of a local deployment you can do something along these lines + change background color trick.

**Comment by borismarin** [comment]
This is finally happening, see https://github.com/OpenSourceBrain/geppetto-osb/issues/30 
shame on you, @stale[Bot]

**Comment by mattearnshaw** [comment]
what remains to be done is a way to propagate theme to widgets properly. for example, plot styles can't in general be controlled by css, they depend on plotly options, so if a new plot is added after theme is switched, we need to ensure it has the correct defaults.

**Comment by tarelli** [comment]
@mattearnshaw is this still going on?

**Comment by tarelli** [comment]
@mattearnshaw ping

**Comment by mattearnshaw** [comment]
@tarelli it's not my priority but it's still an issue

**Comment by pgleeson** [comment]
Would be good to finally polish off... strange that the light background is not persisted in saved/shared projects.
