### ISSUE TITLE
widget (pre-)configuration GUI

### ISSUE THREAD

**Issue by borismarin** [openworm/org.geppetto.frontend#448]
Buttons like the ones that appear under the "spotlight" search bar are a potentially useful way of managing configuration of widgets without having to resort to the command line (see e.g. [how to configure the connectivity widget](http://docs.geppetto.org/en/latest/connectivityW.html)).

See also #447, #388

**Comment by adrianq** [comment]
@borismarin this is the [branch](https://github.com/openworm/org.geppetto.frontend/tree/nsg)

Pending tasks:
- [ ] Use BootstrapMenuMaker for control button and preconfig gui
- [ ] Merge borisOptions and widgetOptions
- [ ] Finish with connectivity options. Decide which ones should be displayed.
- [ ] When a option is selected a submit event is triggered. Not sure why yet...
- [ ] Convert widget into a component <- I will take care of this one
- [ ] Find a place for BootstrapMenuMaker, Button.js, backbone-form.min.js
- [ ] Polish Button.js. Particularly events
- [ ] Send options from preconfig gui to the widgets

**Comment by borismarin** [comment]
@adrianq @LordKrabo I have cleaned up [the prototype](https://github.com/openworm/org.geppetto.frontend/tree/connW-config-gui), still needs CSS-ing but it is functional enough now, and clearly demonstrates what we want to achieve and how it can be done.

Try running `G.configureWidget(6)`

This might be an interesting approach to GUI-centric generation of config objects (@tarelli, @gidili )

(@adrianq I think it will be easier to extend the Radio editor inline instead of having a separated file under widgets/form/vendor as we had before, or even just CSS out the radios into buttons)

**Comment by borismarin** [comment]
I've reverted this back to a much less generic, connec widget-centric solution.
see https://github.com/openworm/org.geppetto.frontend/pull/471
