### ISSUE TITLE
Reduce CPU consumption with smarter THREE.js rendering

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto.frontend#449]
Even when a simulation is paused, Geppetto is eating up at least 30% CPU when it is loaded.  A quick profiling reveals it has to do with THREE.js rendering.

This was discussed over here: https://github.com/mrdoob/three.js/issues/7670 and some workarounds for smarter conditional calling of the render loop were proposed.  One obvious one might relate to only calling it when simulations are running, or just before a PAN/ZOOM action, and then stop rendering when the user is not interacting.  Or it may need to be more complicated.

**Comment by quan-na** [comment]
Will limiting fps solve this problem?
``

      var prevEpoch = Date.now();
      const frameTime = 40; // ~24fps, set 15 for 60fps
      function update () {
        var epoch = Date.now();
        var delta = epoch - prevEpoch;
        prevEpoch = epoch;
        // Draw!
        renderer.render(scene, camera);
        // Schedule the next frame.
        if (delta > frameTime)
          requestAnimationFrame(update);
        else
          window.setTimeout(frameTime - delta, update);
      }
