### ISSUE TITLE
Fix WebGL Support Feedback dialog

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto.frontend#457]
- [ ] Add link to get webgl
- [ ] The spinner should disappear

**Comment by doggan** [comment]
The error feedback works for me (tested in both Chrome and Safari).

<img width="400" src="https://cloud.githubusercontent.com/assets/517857/22321652/628ffbf0-e34b-11e6-954b-88bf023e4502.png">

However, the loading UI displays on top of the error UI, so the text gets covered up. Also the OK button can't be clicked. It might make more sense to remove the OK button and put a link to `https://get.webgl.org/` instead.

**Comment by tarelli** [comment]
@doggan Sure we could put a link to get.webgl.  As for the ok button we can keep it in case there is something meaningful the user could do even without webgl (would depend on the project). The spinner which covers everything should definitely go away, updating this issue. If you want to contribute attempting a fix yourself in a PR feel free to ask more questions, thanks!
