### ISSUE TITLE
Error when changing parameter on experiment console

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.frontend#465]
I loaded an experiment (ACNet2 - Medium Net) with the persistent bundle and every time I try to change any experiment parameter in the experiment console I get a js error like this:
```
Project.getExperimentById(1).simulatorConfigurations['MediumNet'].setSimulator('lemsSimulator')
=> "TypeError: Cannot read property 'simulatorConfigurations' of null"
```

**Comment by pgleeson** [comment]
ACNet medium is multicomp so can't be simulated with jLems. I thought there's a check for supported simulators at some stage. Or maybe it's a bigger issue...

**Comment by adrianq** [comment]
I am not even running the simulation. Those lines are just an example. You will get the same error if you change the timestep, length or if you choose neuron as the simulator. What is not working properly imho is the js executed to update the simulator configuration.

**Comment by jrmartin** [comment]
It does look to be on the js side without hitting the neuroml bundle. How are you loading this project/experiment? It's not one of the default ones installed on persistence, and the ones there are working fine, would like to test it

**Comment by adrianq** [comment]
I have in my machine OSB(redmine) and Geppetto, I am simulation OSB deployment with Geppetto embedded. Geppetto json and xmi is generated on the fly on the OSB side. Find [here](https://github.com/openworm/org.geppetto.frontend/files/392013/MediumNet.tar.gz)
 a tar with the json,xmi and js files generated by OSB. You may have to change this bit http://127.0.0.1:3000 in the json with the url where you finally place the files (you can do it your dropbox folder and make it public). I am already aware that some bits on the js file need to be changed once the next Geppetto version is released.
