### ISSUE TITLE
Refactor the rest of the components to use the new ComponentFactory

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#470]
@adrianq has started a refactoring on the components. The main difference is that the components don't add themselves to the DOM anymore (the initial approach) but are rather added to the DOM by a ComponentsInitialization javascript files which can be customised per each deployment. Logo and LogoSpinner have already been refactored the following is a list of components that still need to be refactored:

- [x] spotlight/spotlight
- [x] controlpanel/controlpanel
- [x] query/query
- [x] share/share
- [x] ExperimentsTable/ExperimentsTable

**Comment by tarelli** [comment]
@gidili can you tick the ones you've done? Thx!

**Comment by LordKrabo** [comment]
Hi @tarelli can I add a milestone for this?

**Comment by gidili** [comment]
@tarelli @LordKrabo all the components are using the factory now, I think this needs to be split for those iter items into different cards
