### ISSUE TITLE
Migrate widgets to be React components

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#491]
- [ ] Design how to have a widget inheriting the API of the widget container (e.g. setName) and the widget specific API (e.g. setData)
- [ ] Refactor the ConnectivityWidget
- [ ] Refactor the WidgetFactory to use the ComponentFactory
- [ ] Refactor the PlotWidget
- [ ] Refactor the PopupWidget
- [ ] Refactor the TreeVisualizerWidget
- [ ] Refactor the VariableVisualizerWidget
- [ ] Refactor the Scatter3DWidget

**Comment by tarelli** [comment]
After we are done with the npm refactoring.

**Comment by tarelli** [comment]
See also #469

**Comment by mattearnshaw** [comment]
@tarelli would it be best to wait for this before I start implementing new widgets eg. https://github.com/OpenSourceBrain/geppetto-osb/issues/10 ?

**Comment by tarelli** [comment]
Interesting https://react-tiles.firebaseapp.com
