### ISSUE TITLE
Improve the way we are hide/showing consoles

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.frontend#495]
Imho [this bit of code](https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/GEPPETTO.Main.js#L203-L221) should be  refactored/moved. 
There are a few things here:
-experimentsButton event should probably be moved to the new component @jrmartin created
-I don't like the idea of changing all the events every time we add a new console. For instance I have added a python console and I have to change all of them. It took a while to understand what was going on with my console as it was not displaying properly. Maybe we can do something smarter using css classes. What do you think @jrmartin?
-I guess for the consoleButton is a little bit tricky as it is not a react component yet.

cc @tarelli @gidili any idea?

**Comment by adrianq** [comment]
Something else to keep in mind is that not all the consoles are gonna be displayed always, i.e. it will depend on the configuration of the componentsinitialization for that environment. For instance VFB does not have experiment console. Not sure how that code will work in this particular case.

**Comment by jrmartin** [comment]
I think best time to refactor that bit will be when we do the refactoring of the console to a React component. We could do something similar like we do for the [ForegroundControls](https://github.com/openworm/org.geppetto.frontend/tree/development/src/main/webapp/js/components/dev/foregroundcontrols) component, new button component might not be best candidate, normal mixing buttons would do with a FooterComponents class handling their toggle/disables states on events.
