### ISSUE TITLE
main.css should not be in the repo

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.frontend#496]
As far as I know main.css is only used in prod environment and it is generated on the fly (using a grunt task?). There is no point to have it in the repo, actually we currently have a very old version.

**Comment by adrianq** [comment]
Also, I would change [this line in geppetto.vm ](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/templates/dist/geppetto.vm#L31). We should have env: "development", otherwise less caches and you can have a lot of fun at 2am trying to figure out what the fuck is going on. There won't be any problem in prod as [these lines](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/templates/dist/geppetto.vm#L29-L42) are removed when compiling with master flag.

I can do all these minor changes but I would like to confirm I am right as I am not a less expert. Am I right @tarelli @gidili @jrmartin?

**Comment by gidili** [comment]
@adrianq that sounds right to me - I had similar problems and every time its hard to remember what it is

**Comment by adrianq** [comment]
Ok, this [PR](https://github.com/openworm/org.geppetto.frontend/pull/497) will change the less configuration.

main.css was not in the repo, my bad. I have it in my local environment.
