### ISSUE TITLE
Disabling/Enabling buttons based on user permissions broken [dev branch]

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto.frontend#499]
Some icons and buttons are not being enabled/disabled properly based on user permissions on the development branch. Looks like ExperimentsControls.js was refactored these past weeks and lost some functionality from usability_actions branch., and the tests didn't catch it

**Comment by tarelli** [comment]
@jrmartin make sure you have the right component initialisation, what buttons are not being enabled/disabled?

**Comment by jrmartin** [comment]
false alarm
