### ISSUE TITLE
Intermittent loading bugs only on loads with empty cache

### ISSUE THREAD

**Issue by slarson** [openworm/org.geppetto.frontend#500]
On an installation with a persistence bundle on development branch:
1. Open a new incognito / private browsing window
2. do the login
3. load an external sample project, say `geppetto?load_project_from_url=https://raw.githubusercontent.com/openworm/org.geppetto.samples/development/UsedInUnitTests/SingleComponentHH/GEPPETTO.json`
4. Click OK on the error message
5. Click the experiment console tab
6. Roll over the experiment row & look at the icons 

Half the time, on @jrmartin 's browser, you can't open the experiment console tab.  Half the time, on mine, you can open the experiment console but the icons include the active & delete icons, which it should not.  The other half of the time, everything loads fine.  Also, if you do enough reloads on the same incognito / private browsing window, eventually it will go away.

@jrmartin could not reproduce it pointing at his own localhost server.  But he was able to reproduce it pointing at my server loading it over the internet.  Possibly the extra latency makes a difference.

This is most likely the cause of the casperjs tests failing on the icons sometimes, because everytime the tests are run they have an empty cache.

**Comment by tarelli** [comment]
@slarson let me know if this is still a problem

**Comment by tarelli** [comment]
@gidili let's remember to check this when re-looking at the casper tests.
