### ISSUE TITLE
Deletes instance

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#508]
If Instances are added then removed then they are still being returned by get instances:
(only background still on scene but previous 4 instances returned).

``````
var potentialInstances = GEPPETTO.ModelFactory.getAllPotentialInstancesEndingWith('_slices');
undefined
potentialInstances
Array[6]0: "VFB_00017894.VFB_00017894_slices"1: "VFB_00000001.VFB_00000001_slices"2: "VFB_00030840.VFB_00030840_slices"3: "VFB_00030870.VFB_00030870_slices"4: "VFB_00030880.VFB_00030880_slices"5: "VFB_00030879.VFB_00030879_slices"length: 6__proto__: Array[0]
VFB_00000001.VFB_00000001_slices
VM2382:1 Uncaught ReferenceError: VFB_00000001 is not defined(…)```
``````

**Comment by gidili** [comment]
@Robbie1977 hey, that's intended, getInstance will return you the instance if it exists or create it if it doesn't. I get it that it's confusing because it's undocumented as it's an injected method on the global top level Instances array. 

If you want to check if an instance exists the only way right now is to eval the instance path and see if it's undefined (which is what getInstance does before it creates it if it's not already there).

@tarelli can you think of any other way to check if an instance exists?

**Comment by gidili** [comment]
@Robbie1977 I stand corrected - I forgot there is way to do what you want with getInstance, given [the signature](https://www.dropbox.com/s/4aaul59zfr2ccl4/Screenshot%202016-10-28%2001.15.06.png?dl=0):

`instances.getInstance = function (instancePath, create)`

You can pass the 2nd arg as false and it will not create it if it doesn't exist and should return an empty array.

**Comment by gidili** [comment]
@Robbie1977 to clarify in your example, getAllPotentialInstancesEndingWith always gets you back instance paths of **potential** instances, regardless if they exist of not. 

If you do getInstance with the 2nd parameter set to false on those paths, they will not get created if they don't already exist.

**Comment by Robbie1977** [comment]
The issue with using getInstance with false create is that it fails to create on the initial run.

@gidili Is there a way to tell if the instance has just been created as opposed to been deleted?

**Comment by tarelli** [comment]
@Robbie1977 @gidili let's add to the loading script a getInstance for all the slices when we fetch a new variable so that getInstance(...,false) will work.

**Comment by tarelli** [comment]
Let's factor out when the instances are created maybe into a function, at the moment it seems to be spread a bit all over, see https://github.com/VirtualFlyBrain/geppetto-vfb/blob/master/ComponentsInitialization.js#L77

**Comment by gidili** [comment]
@Robbie1977 I think this got resolved right?
