### ISSUE TITLE
wrong aspect when adding new experiment

### ISSUE THREAD

**Issue by mattearnshaw** [openworm/org.geppetto.frontend#534]
if there are no experiments, then any new ones have the wrong aspect which means simulations won't run.

eg. for HH, the default experiment has aspect `HHCellNetwork`, if we delete this and add a new one then the aspect becomes `HHCellNetwork(HHCellNetwork)`.

I was trying to debug this for a while but didn't catch the issue yet...

**Comment by tarelli** [comment]
@mattearnshaw I think it's not a problem of the "aspect" but rather the default experiment created by OSB has all the properties for the run configured, so called aspectConfiguration (the simulator, length, timestep, etc) while a new experiment won't have them (Geppetto wouldnt know what they are unless it's told)
