### ISSUE TITLE
Parameters view in Control Panel

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto.frontend#555]
![selection_183](https://cloud.githubusercontent.com/assets/1556687/23025805/07b84a8a-f457-11e6-8f9d-7bcf0d1becd9.png)

- [x] Icon for parameters could be updated, looks like "enter"; opposite sign used on OSB for log out...
- [x] Should be made clearer (tooltip/warning) that you can only change parameter values when you are in the DESIGN stage; need to duplicate experiment to continue (in screenshot above I can place the cursor, but nothing happens when I type...)

**Comment by pgleeson** [comment]
Reopening as it's still not clear for users...

**Comment by pgleeson** [comment]
Needs to be addressed some time...

**Comment by mattearnshaw** [comment]
https://github.com/openworm/org.geppetto.frontend/tree/cpEnhance
