### ISSUE TITLE
Establish convention to format Javascript files same as we did for Java.

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#562]

**Comment by pgleeson** [comment]
@tarelli Where is the recommended format for Java described?

**Comment by tarelli** [comment]
https://github.com/openworm/org.geppetto/blob/master/eclipse/GeppettoFormatter.xml

**Comment by tomkel** [comment]
Check out [prettier-eslint](https://github.com/prettier/prettier-eslint).
