### ISSUE TITLE
Missing rotation from camera controls

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#597]
incrementCameraRotate is ignoring the 3rd variable after it passes it to incrementRotationEnd:
https://github.com/openworm/org.geppetto.frontend/blob/4e2524359f030720ab6c38298137a4c98913a799/src/main/webapp/js/components/interface/3dCanvas/TrackballControls.js#L677

This results in only being able to rotate the image in X and Y but not Z (rotate view counter/clockwise).

Whist you can do it by a complicated wiggle if you rotate the cursor round the centre point this is missing an essential control to 3D navigation.

**Comment by tarelli** [comment]
Might be relevant http://stackoverflow.com/questions/11627727/three-js-trackballcontrols-js-rotating-in-z-x-axis-only

**Comment by tarelli** [comment]
This was added
