### ISSUE TITLE
disable state storage server side

### ISSUE THREAD

**Issue by mattearnshaw** [openworm/org.geppetto.frontend#646]
currently we have the problem that the state of the OSB samples (Anonymous User projects) is being saved. I can add `G.enableLocalStorage(false)` to the `script.js` of these, but obviously this is not enough. Maybe it already exists- I'm looking for something like a database setting that would reject state storage. @gidili ?

**Comment by mattearnshaw** [comment]
awaiting https://github.com/openworm/org.geppetto.simulation/pull/131

**Comment by gidili** [comment]
@mattearnshaw do you need that PR merged if the frontend one was merged already? I would expect that scenario never to arise given then changes on frontend?

**Comment by mattearnshaw** [comment]
@gidili ah yeah, looking again I think you're right
