### ISSUE TITLE
Having trouble deploying Geppetto

### ISSUE THREAD

**Issue by vamsi1994** [openworm/org.geppetto.frontend#693]
> Alright we have an error at least! Can you please paste the full output of mvn install on org.geppetto.frontend? Thanks!

@tarelli Maven install log: [https://gist.github.com/vamsi1994/4f2e8a5241a067b33826222cb1d6843c](https://gist.github.com/vamsi1994/4f2e8a5241a067b33826222cb1d6843c).

**Comment by mattearnshaw** [comment]
This is because the args "${embedded}" etc. are evaluating to literals rather being treated as (possibly empty) BASH variables, on Windows. My suggestion is apply the following diff in `org.geppetto.frontend/master/src/main/webapp/webpack.config.js`:
https://gist.github.com/mattearnshaw/aed304fe43bc851426e320d891ad079c. This issue should be obsolete in the next release.

**Comment by vamsi1994** [comment]
@mattearnshaw The GUI issue has been fixed, Thanks. But now I've run into a new problem. It's throwing an error when I try to open/run any of the demo **simulation** experiments.

Here's the error log: 
```
Houston, we have a problem...
Error playing the experiment 1

Details
org.geppetto.core.common.GeppettoExecutionException: java.lang.NullPointerException
```

**Comment by mattearnshaw** [comment]
@vamsi1994 could you check the virgo log and paste the full stack trace for this exception? the log usually lives at `serviceability/logs/log.log` inside the virgo root.

**Comment by vamsi1994** [comment]
@mattearnshaw Log: [https://gist.github.com/vamsi1994/954cb43e4f412e27ffbc15f5ac662810](https://gist.github.com/vamsi1994/954cb43e4f412e27ffbc15f5ac662810)

**Comment by mattearnshaw** [comment]
@vamsi1994 thanks. Notice:
```
[2017-10-19 15:39:01.814] ERROR ... java.lang.UnsatisfiedLinkError: no jhdf5 in java.library.path
```
could you try installing the HDF Java binary from [here](https://support.hdfgroup.org/products/java/release/download.html)?

also notice:
```
java.library.path: C:\Program Files\Java\jdk1.8.0_144\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Python27;C:\Python27\Lib;C:\Python27\Scripts;C:\Program Files\Java\jdk1.8.0_144;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Users\lords\Downloads\GeppettoPrerequisiteSoftware\apache-maven-3.5.0\bin;C:\Program Files\Git\cmd;C:\Users\lords\AppData\Local\Microsoft\WindowsApps;.
```
I expect it's looking for something like `jhdf5.dll` in one of these directories – installing HDF Java should take care of this.

**Comment by tarelli** [comment]
that's weird though, the HDF5 libraries should contain the native without any need to install anything else @jrmartin you are also on windows, have you ever had problems with this?

**Comment by vamsi1994** [comment]
@mattearnshaw @tarelli Installing HDF Java binary did not fix the problem. So, I copied the `jhdf5.dll` into `C:\Program Files\Java\jdk1.8.0_144\bin` directory myself. I'm able to run the simulations now. Some of the plot widgets are not working though, they're just blank.

![screenshot 2](https://user-images.githubusercontent.com/6739759/31779359-9bc80ba0-b510-11e7-9c17-29e5ad6f2991.png)

![screenshot 5](https://user-images.githubusercontent.com/6739759/31779527-f40717fc-b510-11e7-920a-3e6fb97bb7d5.png)

**Comment by tarelli** [comment]
@vamsi1994 glad to see progress, thanks for getting us more feedback! Could you check using the development branch for all the bundles? We are fixing some of those issue for the new release next week. You can switch branches for everything using the gitall.py script in the utilities/source_setup/ folder of org.geppetto, e.g. `python gitall.py checkout development` `python gitall.py pull`

**Comment by jrmartin** [comment]
@tarelli Yes I have. The hdf5-java-bindings jar needs some updating to fix a glitch

**Comment by tarelli** [comment]
@jrmartin cool looks like we have a fix that we need to push for HDF5 @vamsi1994 will incorporate it for the next release

**Comment by tarelli** [comment]
@vamsi1994 HDF5 fix is in development https://github.com/openworm/org.geppetto.core/commit/c99155eea465dc8447445a42992a1291a0edfd3a
