### ISSUE TITLE
Add option to select multiple models at "Your models" tab to delete

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto.frontend#719]
Persisted models quickly build up & it would be good to quickly be able to prune this set.

(think this may be duplicate issue...)

**Comment by mattearnshaw** [comment]
https://github.com/ThibaultJanBeyer/DragSelect

**Comment by pgleeson** [comment]
Would still be good to have...

**Comment by pgleeson** [comment]
Still needed...

**Comment by pgleeson** [comment]
Still required..

**Comment by pgleeson** [comment]
Would be good...

**Comment by pgleeson** [comment]
One day my issue will be solved...

**Comment by pgleeson** [comment]
Still required..

**Comment by tarelli** [comment]
To be moved to geppetto-client
