### ISSUE TITLE
aliasing on certain platforms

### ISSUE THREAD

**Issue by mattearnshaw** [openworm/org.geppetto.frontend#724]
![alias](https://user-images.githubusercontent.com/679927/34004967-632ae620-e0f1-11e7-9288-2915eafde5ab.png)

* Arch Linux 4.14.4
* Chromium Version 63.0.3239.84 (Developer Build) (64-bit)
* [chrome://gpu](http://mattearnshaw.com/gpu.html) (Intel HD Graphics 520)
* also on Firefox 57.0.2 (64-bit)

**Comment by mattearnshaw** [comment]
perhaps @pgleeson can provide information about his machines

**Comment by pgleeson** [comment]
Can't say I've ever had anti-aliasing working successfully...

Firefox on Ubuntu 16.4, NVIDIA Quadro M4000/PCIe/SSE2:
![selection_464](https://user-images.githubusercontent.com/1556687/34053315-3c1ac4b0-e1be-11e7-9823-d9788f26cd6f.png)
Same machine Chromium: 
![selection_465](https://user-images.githubusercontent.com/1556687/34053345-5254fd90-e1be-11e7-903d-ee84f709e383.png)
Chrome on Mac Book Pro 2016, Sierra
<img width="261" alt="screen shot 2017-12-15 at 17 35 51" src="https://user-images.githubusercontent.com/1556687/34053378-89e51a9c-e1be-11e7-9ede-c33b6bc9106d.png">
Same in Firefox:
<img width="319" alt="screen shot 2017-12-15 at 17 38 12" src="https://user-images.githubusercontent.com/1556687/34053500-fb03005e-e1be-11e7-9831-a46e2636b4cf.png">

**Comment by pgleeson** [comment]
On a Windows 10 machine...
Top one seems better, but white is still bad... Anyone have anything better then this?
![capture](https://user-images.githubusercontent.com/1556687/34112775-890345ec-e405-11e7-9f47-d5942c460afa.PNG)
![capture1](https://user-images.githubusercontent.com/1556687/34112776-8c06a04a-e405-11e7-8136-2dfe94daefde.PNG)

**Comment by mattearnshaw** [comment]
turns out [removing `CopyShader`](https://github.com/openworm/org.geppetto.frontend/commit/555763a5540fc7c4d09adb47ecdb2924a8f58b5c) fixes this issue, or at least reduces aliasing significantly… now can anyone proffer a reason as to why the `CopyShader` exists to start with?

![1](https://user-images.githubusercontent.com/679927/34610634-e841e820-f219-11e7-821e-0d8312cddbd3.png)

**Comment by tarelli** [comment]
@mattearnshaw I think CopyShader can be safely removed there, problem might be connected to this https://github.com/mrdoob/three.js/issues/568.

**Comment by mattearnshaw** [comment]
@tarelli thanks, I will open a PR. and yes, I discovered this while trying to apply FXAA, which actually seemed to make things worse. in the meantime, osb.org has this fix, and can be compared with the original code on comodl

**Comment by pgleeson** [comment]
Updated version works v nicely on Mac retina display:
<img width="915" alt="screen shot 2018-01-05 at 13 52 01" src="https://user-images.githubusercontent.com/1556687/34612000-cd31a57e-f21f-11e7-9228-3b68d12752fb.png">

**Comment by tarelli** [comment]
Fantastic, great catch @mattearnshaw!

**Comment by borismarin** [comment]
Might be relevant to this issue: no significant aliasing when displaying static figs:
<img width="351" alt="screen shot 2018-01-05 at 12 50 48" src="https://user-images.githubusercontent.com/3452783/34614007-2286c3d2-f217-11e7-9412-4e16dc43604a.png">
but horrible when auto rotation is toggled via the 'camera' button:
<img width="326" alt="screen shot 2018-01-05 at 12 52 14" src="https://user-images.githubusercontent.com/3452783/34614060-5111bbf8-f217-11e7-9c24-8cbc2d82934b.png">

**Comment by mattearnshaw** [comment]
according to https://docs.unity3d.com/Manual/webgl-graphics.html:

> Note that on WebGL1.0 there are several limitations
> * Any post-processing effect applied to the camera disables the built-in Anti-Aliasing.
…
There are no such limitations on WebGL2.0.

It seems like most browsers support WebGL 2 now, so switching to [`WebGL2Renderer`](https://github.com/mrdoob/three.js/issues/9965) might be better. I will try it out

**Comment by mattearnshaw** [comment]
Can't get `WebGL2Renderer` to work, even with updating Three to 0.89 – says it's not a constructor.
