### ISSUE TITLE
play button broken

### ISSUE THREAD

**Issue by mattearnshaw** [openworm/org.geppetto.frontend#736]
try playing the Izhikevich sample project using the Play button (works if you use "Play Step by Step" in Results, but not with them main button) http://opensourcebrain.org/projects/izhikevichmodel?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FOpenSourceBrain%2FIzhikevichModel%2Fsample%2FosbSessions%2Fsample%2FSample_Session.json

**Comment by tarelli** [comment]
@mattearnshaw is this still happening?

**Comment by mattearnshaw** [comment]
@tarelli yes. `ExperimentNode.play` (menu "Play step by step") works but not `ExperimentNode.playAll' (main Play button). however, I'm now wondering what the difference between `play` and `playAll` is supposed to be...
