### ISSUE TITLE
Create tabbed drawer component

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#784]
- [x] Investigate existing libraries
- [x] Create new branch
- [x] Create new React component that can:
   - [x] Support multiple embeddable components (e.g. Console, Python Console, Experiments Table), this needs to really work with any component
   - [x] Resize in height
   - [x] Maximize in height / Restore to previously set height / Minimize in height (closed drawer)
- [x] Remove old code in Geppetto Main (also look in other places) that hardcodes the current tab
- [x] Clean the geppetto.ejs template to remove hardcoded divs
- [x] Update Geppetto default extension to use the new component
- [x] Add casper tests to test the new component, make sure they pass
- [x] Open PR

**Comment by gidili** [comment]
@tarelli along the same lines we could re-use the tab component to get rid of that simple tabs dependency from the query  /query results component after this

**Comment by gidili** [comment]
This is done
