### ISSUE TITLE
Remove analysis not always working

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#803]

**Comment by ddelpiano** [comment]
![Screen Shot 2018-05-23 at 12.10.51.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aba674504f5460012ef47bc/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f06b7191a379ed0c2a51415a4fbe5d4a1f06a3a3dc78e2a436628f5f08edd86f5c71c16f45ace98018ea50e972d84e83b1ea9850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca5ff64ce54e54ac1b3161f43b.png)

Another issue noticed playing with it is that you can add multiple times the average, even if already there.
