### ISSUE TITLE
Make 'persist' more user understandable

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto.frontend#806]
Comment from @mrio:
"I still feel that ‘the project is getting persisted’ is odd phrasing. Maybe ‘add to dashboard’ would be a simpler alternative? Then the tutorials simply have to say ‘add the project to the dashboard for changing parameters’"

Maybe "Save this model to your dashboard to running simulations"...

**Comment by pgleeson** [comment]
Still think this is relevant...

**Comment by tarelli** [comment]
To be moved to geppetto-osb
