### ISSUE TITLE
Titles in the plot are showing up gray

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#863]
It happens with the latest from development, check https://livedev.geppetto.org (continuous deployment yay! https yay!)

**Comment by tarelli** [comment]
<img width="523" alt="screenshot 2019-01-11 at 13 57 17" src="https://user-images.githubusercontent.com/81127/51037764-08096300-15a9-11e9-98ab-f44e0786f562.png">

**Comment by Robbie1977** [comment]
Coming from rgb(68, 68, 68) but can't figure out where it comes from!?
```<text class="ytitle" transform="rotate(-90,12,104)" x="12" y="104" text-anchor="middle" data-unformatted="Electric potential (V)" data-math="N" style="font-family: &quot;Open Sans&quot;, verdana, arial, sans-serif; font-size: 14px; fill: rgb(68, 68, 68); opacity: 1; font-weight: normal; white-space: pre;">Electric potential (V)</text>```

**Comment by tarelli** [comment]
Fixed by @mattearnshaw PR, thanks!
