### ISSUE TITLE
Add to Plot doesn't work with last added plot in Control Panel

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.geppetto.frontend#876]
To reproduce:
1) Add a new plot with a recorded variable in Control Panel
2) Try to Add to Plot for this, but the new plot is not listed.

After closing the Control Panel & reopening the new plot is now in the list for Add to Plot

See also:
https://github.com/OpenSourceBrain/geppetto-osb/issues/197
https://github.com/OpenSourceBrain/geppetto-osb/issues/196

**Comment by pgleeson** [comment]
Still an issue...

**Comment by tarelli** [comment]
To be reopened in geppetto-client
